version: "3"

services:
  backend:
    build: ./backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file: ./backend/.env

  frontend:
    build: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  frontend:
  backend:
  mongo_data:
